name: logblock

services:
  back-end:
    build:
      context: src/back-end
      tags:
        - "logblock/back-end"
    hostname: back-end
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db:
    build:
      context: src/database
      tags:
        - "logblock/database"
    hostname: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=logblock-db
      - POSTGRES_PASSWORD=logblock_secrets_321@
      - POSTGRES_DB=logblock
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/usr/local/share/pgdata'