name: logblock

services:
  back-end:
    build:
      context: src/back-end
      tags:
        - "logblock/back-end"
    hostname: back-end
    ports:
      - 8080:8080
    networks: 
      - app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./src/back-end/.env
    restart: always
  
  db:
    build:
      context: src/database
      tags:
        - "logblock/database"
    hostname: db
    ports:
      - 5432:5432
    networks: 
      - app
    environment:
      - POSTGRES_USER=logblock-db
      - POSTGRES_PASSWORD=logblock_secrets_321@
      - POSTGRES_DB=logblock
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always

  front-end:
    build:
      context: src/front-end
      tags:
        - "logblock/front-end"
    hostname: front-end
    ports:
      - "3000:3000"
    networks: 
      - app
    env_file:
      - ./src/front-end/.env
    restart: always

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/usr/local/share/pgdata'
networks: 
  app:
